// ── Roadmap Data for 1,000 Blog Posts ──
// Source: content/strategy/ (internal planning docs)
// All topic titles are from the strategy files

export interface SubCategory {
    name: string;
    postRange: string;
    topicCount: number;
    topics: string[];
}

export interface Category {
    id: string;
    name: string;
    nameHindi: string;
    slug: string;
    icon: string;
    description: string;
    totalPosts: number;
    postRange: string;
    subCategories: SubCategory[];
}

export interface Formula {
    name: string;
    description: string;
    example: string;
    estimatedTopics: number;
}

export const roadmapCategories: Category[] = [
    {
        id: "cat-4",
        name: "Idioms, Phrases & Phrasal Verbs",
        nameHindi: "मुहावरे, वाक्यांश और Phrasal Verbs",
        slug: "idioms-phrases-phrasal-verbs",
        icon: "💬",
        description:
            "Phrasal verb families (Look, Get, Take, etc.) with 4 posts each (Basic, Advanced, PYQs, Quiz) + theme-based idioms by topic (Animals, Colors, Body Parts, etc.) + year-wise SSC/Banking PYQ analysis.",
        totalPosts: 210,
        postRange: "Posts 1–210",
        subCategories: [
            {
                name: "Phrasal Verbs by Verb Family",
                postRange: "Posts 1–80",
                topicCount: 80,
                topics: [
                    "Look (4 posts): Basic list, Confusing cases, PYQs, Quiz",
                    "Get (4 posts): Top 15, Advanced, Bank/SSC PYQs, Fill-in-blanks",
                    "Take (4 posts): Common, Confusing, PYQs, Practice Quiz",
                    "Put (4 posts): Important, Master, SSC PYQs, Interactive Quiz",
                    "Bring (4 posts): Basic, Advanced, Expected Exam Qs, Quiz",
                    "Call (4 posts): Important, Stories, SSC/Banking PYQs, Practice Test",
                    "Run (4 posts): Common, Advanced, PYQs, Matching Quiz",
                    "Set (4 posts): Basic, Confusing, TCS PYQs, Weekly Review",
                    "Break (4 posts): Key, Advanced, Repeated PYQs, Practice Test",
                    "Make (4 posts): Basic, Advanced, Recent Exams, Grammar Quiz",
                    "Turn (4 posts), Keep (4 posts), Come (4 posts), Give (4 posts)",
                    "Fall (4 posts), Carry (4 posts), Go (4 posts), Pass (4 posts)",
                    "Stand (4 posts), Hold (4 posts)",
                ],
            },
            {
                name: "Theme-Based Idioms",
                postRange: "Posts 81–130",
                topicCount: 50,
                topics: [
                    "Animals & Birds Idioms (2 posts: List + Mock Test)",
                    "Color-Based Idioms (2 posts: Red/Blue/Green/Black/White)",
                    "Body Parts Idioms (2 posts: Hand, Eye, Foot, Head)",
                    "Food & Eating Idioms (2 posts)",
                    "Time & Clocks Idioms (2 posts)",
                    "Money & Finance Idioms (2 posts)",
                    "Weather & Nature Idioms (2 posts)",
                    "Numbers & Math Idioms (2 posts)",
                    "Clothes & Fashion Idioms (2 posts)",
                    "Relationships & Friendship Idioms (2 posts)",
                    "Success & Failure Idioms (2 posts)",
                    "Anger & Emotions Idioms (2 posts)",
                    "Health & Sickness Idioms (2 posts)",
                    "Travel & Motion Idioms (2 posts)",
                    "Work & Office Idioms (2 posts)",
                    "Music & Art, Books & Education, Sports & Games (6 posts)",
                    "Fire & Water, Household Objects, Tools & Weapons (6 posts)",
                    "Sleep & Dreams, Law & Justice, Geography & Earth (6 posts)",
                    "War & Peace Idioms (2 posts)",
                ],
            },
            {
                name: "SSC Previous Year Idioms (Year-wise)",
                postRange: "Posts 131–170",
                topicCount: 40,
                topics: [
                    "SSC CGL 2018–2026 year-wise (12 posts: each year)",
                    "SSC CHSL 2020–2026 year-wise (7 posts)",
                    "SSC MTS 2020–2026 year-wise (7 posts)",
                    "SSC CPO 2020–2026 year-wise (7 posts)",
                    "SSC Selection Post & Stenographer Expected Idioms (4 posts)",
                    "Top 50 Repeated TCS Pattern Idioms, 100 Hardest Idioms (3 posts)",
                ],
            },
            {
                name: "Bank, Defense & State Exams Idioms",
                postRange: "Posts 171–210",
                topicCount: 40,
                topics: [
                    "SBI PO & Clerk Specific (10 posts)",
                    "IBPS PO & Clerk Specific (10 posts)",
                    "RBI Grade B & LIC Exams (8 posts)",
                    "Defense Exams: NDA, CDS, CAPF, Airforce, Navy (8 posts)",
                    "State PCS & Civil Services English (4 posts)",
                ],
            },
        ],
    },
    {
        id: "cat-3",
        name: "Grammar Rules & Error Spotting",
        nameHindi: "व्याकरण के नियम और त्रुटि पहचान",
        slug: "grammar-error-spotting",
        icon: "📝",
        description:
            "Complete grammar coverage with TCS pattern: each post follows 'Grammar Rule + English-Hindi Examples + 10 PYQs + Bilingual Solutions' format. Covers all parts of speech with error spotting.",
        totalPosts: 200,
        postRange: "Posts 211–410",
        subCategories: [
            {
                name: "Noun Rules & Error Spotting",
                postRange: "Posts 1–20",
                topicCount: 20,
                topics: [
                    "Nouns that look plural but are singular (with Hindi Meanings)",
                    "Nouns that look singular but are always plural",
                    "Uncountable Nouns Traps (Scenery, Information, Advice)",
                    "Singular/Plural Confusions (Phenomenon, Criteria, Oasis)",
                    "Apostrophe 's' Rules Part 1: Joint vs Separate Possession",
                    "Apostrophe 's' Rules Part 2: Non-living things exceptions",
                    "Compound Noun Errors (Sons-in-law vs Brother-in-laws)",
                    "Noun Repeating Rule: Noun + Preposition + Noun singular",
                    "Collective Nouns Agreement (Jury, Committee, Audience)",
                    "Nouns indicating numbers (Dozen, Score, Million)",
                    "Noun Case Errors: Subjective vs Objective traps",
                    "Confusing Noun Pairs (Custom vs Habit, Cause vs Reason)",
                    "Confusing Noun Pairs (House vs Home, Client vs Customer)",
                    "Gender-based Noun Errors (Actor/Actress rules)",
                    "Top 20 Noun Errors SSC CGL Tier-1 (Bilingual)",
                    "Bank Exams Noun Error Spotting + Fractional Nouns",
                    "TCS Pattern Noun Practice Test (20 Questions)",
                    "SSC Sentence Improvement Noun Practice Set",
                    "Advanced Noun Rules for SBI PO & IBPS PO",
                    "Mega Revision Quiz: 50 Noun Questions",
                ],
            },
            {
                name: "Pronoun Rules & Error Spotting",
                postRange: "Posts 21–40",
                topicCount: 20,
                topics: [
                    "Rule of 231 and 123: Personal Pronoun Arrangement",
                    "Relative Pronoun WHO vs WHOM (Easiest Trick)",
                    "Relative Pronoun THAT vs WHICH (Bilingual)",
                    "WHOSE vs OF WHICH (living/non-living things)",
                    "Pronoun Case after THAN and AS",
                    "Pronoun Case after LET and BUT/EXCEPT",
                    "Distributive Pronouns (Each, Every, Either, Neither)",
                    "Difference: EACH OTHER vs ONE ANOTHER (SSC PYQs)",
                    "Reflexive Pronoun Traps (Acquit, Avail, Adapt verbs)",
                    "Verbs that never take Reflexive Pronouns",
                    "Rules of ONE and ONES (Pronoun Agreement)",
                    "Pronoun Case with Gerund (My going vs Me going)",
                    "Pronoun-Antecedent Agreement with Collective Nouns",
                    "IT vs THIS Differences and Usage Rules",
                    "Top 20 Pronoun Errors SSC CHSL & MTS",
                    "High-Level Pronoun Questions for Bank PO Prelims",
                    "Pronoun Error Spotting for NDA & CDS",
                    "SSC Sentence Improvement Pronoun Practice Set",
                    "Common Pronoun Mistakes Hindi-Medium Students",
                    "Mega Revision Quiz: 50 Pronoun Questions",
                ],
            },
            {
                name: "Adjective & Determiner Rules",
                postRange: "Posts 41–60",
                topicCount: 20,
                topics: [
                    "Adjective Order (OSASCOMP rule in Hindi)",
                    "FEW vs A FEW vs THE FEW (Ultimate Guide)",
                    "LITTLE vs A LITTLE vs THE LITTLE",
                    "ELDER/ELDEST vs OLDER/OLDEST (SSC PYQs)",
                    "FARTHER vs FURTHER with Examples",
                    "NEAREST vs NEXT with Exam Questions",
                    "Comparatives taking TO instead of THAN",
                    "Double Comparatives/Superlatives Errors",
                    "Adjectives that cannot be compared",
                    "AS...AS vs SO...AS Rules",
                    "Cardinal vs Ordinal Adjectives Order",
                    "Adjective ending in LY (Cowardly, Miserly, Friendly)",
                    "Hypothesis Adjectives (Look, Taste, Smell verbs)",
                    "Much vs Many (Determiner Rules)",
                    "Each vs Every (Grammatical Differences)",
                    "Top 20 Adjective Errors TCS Pattern SSC",
                    "High-Level Determiner for SBI Clerk & IBPS PO",
                    "SSC Sentence Improvement Adjective Practice",
                    "Adjective Errors in CDS & NDA Papers",
                    "Mega Revision Quiz: 50 Adjective Questions",
                ],
            },
            {
                name: "Verb & Non-Finite Verb Rules",
                postRange: "Posts 61–80",
                topicCount: 20,
                topics: [
                    "Transitive vs Intransitive Verbs Error Spotting",
                    "Confusing: LIE (lie) vs LIE (lay) vs LAY",
                    "Confusing: RISE vs RAISE vs ARISE",
                    "Confusing: HANG (execute) vs HANG (suspend)",
                    "AFFECT vs EFFECT with Hindi Examples",
                    "ADVISE vs ADVICE Grammar Rules",
                    "PRACTISE vs PRACTICE (SSC Error Detection)",
                    "Gerund vs Infinitive Part 1: Verbs taking Gerund",
                    "Gerund vs Infinitive Part 2: Verbs taking Infinitive",
                    "BARE INFINITIVE Rules (Bid, Let, Make, Help)",
                    "Bare Infinitive after Had better, Would rather",
                    "Verbs taking Gerund after Prepositions",
                    "Dangling Participle Errors identification",
                    "Present Participle vs Past Participle Errors",
                    "Modal Verbs (Should, Must, Ought to differences)",
                    "Can vs Could and May vs Might rules",
                    "Top 20 Verb & Non-Finite Errors SSC Exams",
                    "High-Level Verb Error for Bank PO Mains",
                    "SSC Sentence Improvement Verb Practice",
                    "Mega Revision Quiz: 50 Verb Questions",
                ],
            },
            {
                name: "Subject-Verb Agreement (SVA)",
                postRange: "Posts 81–105",
                topicCount: 25,
                topics: [
                    "Basic Rule: Singular subject → Singular verb",
                    "Two Subjects joined by AND (exceptions)",
                    "Nouns as single idea (Bread and butter rule)",
                    "AS WELL AS, ALONG WITH, WITH rules",
                    "EITHER...OR, NEITHER...NOR rules",
                    "Agreement with EACH, EVERY, EVERYONE",
                    "ONE OF THE + Plural Noun rule",
                    "ONE OF THE + Relative Pronoun rule",
                    "MANY A + Singular Noun rule",
                    "A GREAT MANY / A GOOD MANY rule",
                    "A NUMBER OF vs THE NUMBER OF",
                    "Collective Nouns (Unanimous vs Divided)",
                    "Distances/Weight/Height/Money (Singular Verb)",
                    "Nouns plural in form but singular in meaning",
                    "Nouns like Clergy, Gentry, Poultry",
                    "NONE and ANY (Singular vs Plural)",
                    "Fractions and Percentages rules",
                    "THERE and IT introductory subjects",
                    "Conditional Sentences with WERE",
                    "Top 25 SVA Errors Recent SSC Exams",
                    "Bank PO English: Hard SVA Questions",
                    "SVA Error Spotting for NDA/CDS/CAPF",
                    "SVA Practice for State PCS Exams",
                    "SSC Sentence Improvement SVA Practice",
                    "Mega Revision Quiz: 50 SVA Questions",
                ],
            },
            {
                name: "Adverb Rules & Error Spotting",
                postRange: "Posts 106–120",
                topicCount: 15,
                topics: [
                    "Adverb Position: MPT Rule (Manner, Place, Time)",
                    "Rule of ENOUGH (Before Nouns, After Adjectives)",
                    "TOO vs VERY (Positive/Negative meanings)",
                    "INVERSION Part 1: Scarcely, Hardly, Seldom, Barely",
                    "INVERSION Part 2: Under no circumstances, Only then",
                    "HARD vs HARDLY (Confusing Adverb Pairs)",
                    "LATE vs LATELY with Exam Examples",
                    "FREE vs FREELY (Bilingual Explanations)",
                    "Negative Adverbs (No double negatives rule)",
                    "Adverbs after Transitive vs Intransitive Verbs",
                    "Top 15 Adverb Errors SSC Exams",
                    "High-Level Adverb Error for Bank PO/Clerk",
                    "SSC Sentence Improvement Adverb Practice",
                    "Adverb Errors in NDA, CDS, Defense Exams",
                    "Mega Revision Quiz: 50 Adverb Questions",
                ],
            },
            {
                name: "Preposition & Fixed Preposition Rules",
                postRange: "Posts 121–150",
                topicCount: 30,
                topics: [
                    "BETWEEN vs AMONG (Rules & exceptions)",
                    "BESIDE vs BESIDES (Hindi Meanings)",
                    "SINCE vs FOR in Perfect Tenses",
                    "ACROSS vs THROUGH (Illustrations)",
                    "IN vs INTO and ON vs ONTO Rules",
                    "BY vs WITH (Agent vs Instrument in Passive)",
                    "DURING vs WHILE with Examples",
                    "Omission of Prepositions (Discuss, Describe, Order)",
                    "Omission before Time Expressions",
                    "Prepositions after Adjectives (Angry with vs at)",
                    "Prepositions after Verbs (Agree with/to/on)",
                    "Prepositions after Nouns (Blind in vs to)",
                    "Die of vs Die from (Disease vs External cause)",
                    "Fixed Preposition List A-C (SSC Repeated)",
                    "Fixed Preposition List D-F (Bank Exams)",
                    "Fixed Preposition List G-I (High-Yield)",
                    "Fixed Preposition List J-L (State PCS)",
                    "Fixed Preposition List M-O (CDS/NDA)",
                    "Fixed Preposition List P-R (Bilingual)",
                    "Fixed Preposition List S-U (TCS Pattern)",
                    "Fixed Preposition List V-Z (Master List)",
                    "Prepositions at end of sentences",
                    "Top 30 Preposition Errors SSC Exams",
                    "High-Level Fixed Preposition Cloze Test Bank PO",
                    "Preposition Errors in UPSC CAPF Descriptive",
                    "SSC Sentence Improvement Preposition Practice",
                    "Prepositions in Daily Conversation (Bilingual)",
                    "Preposition Mistakes Hindi Medium Students",
                    "Preposition Questions State PCS English",
                    "Mega Revision Quiz: 50 Preposition Questions",
                ],
            },
            {
                name: "Conjunction Rules & Error Spotting",
                postRange: "Posts 151–165",
                topicCount: 15,
                topics: [
                    "EITHER...OR, NEITHER...NOR Parallel Structure",
                    "NOT ONLY...BUT ALSO Parallel Structure",
                    "Rule of LEST: Only SHOULD/V1 after Lest",
                    "Rule of NO SOONER: Use THAN with Inversion",
                    "Rule of HARDLY/SCARCELY: Use WHEN with Inversion",
                    "ALTHOUGH/THOUGH and YET Rules",
                    "AS IF and AS THOUGH (Subjective Mood)",
                    "SO...THAT vs TOO...TO Conversion",
                    "BECAUSE/AS/SINCE: No Therefore/So after them",
                    "THAT vs WHETHER/IF (Doubtful/Sure sentences)",
                    "Top 20 Conjunction Errors SSC CGL & CHSL",
                    "High-Level Conjunction for Bank Exams",
                    "SSC Sentence Improvement Conjunction Practice",
                    "Conjunction Error Spotting NDA & CDS",
                    "Mega Revision Quiz: 50 Conjunction Questions",
                ],
            },
            {
                name: "Tenses & Conditional Sentences",
                postRange: "Posts 166–185",
                topicCount: 20,
                topics: [
                    "Present Simple vs Continuous: State Verbs",
                    "Present Perfect vs Past Simple (Time Markers)",
                    "Past Simple vs Past Perfect (Two actions)",
                    "Since/For in Perfect Continuous Tenses",
                    "Future Tense: No future in time/conditional clauses",
                    "Conditional Type 0: Zero Conditional",
                    "Conditional Type 1: First Conditional",
                    "Conditional Type 2: Second Conditional",
                    "Conditional Type 3: Third Conditional",
                    "Hypothetical Wishes (I wish I were / If only)",
                    "Conditional Inversion (Had I known, Were I you)",
                    "Habitual vs Temporary Actions in Tenses",
                    "IT'S TIME / IT'S HIGH TIME (V2 after these)",
                    "Future Perfect with By the time",
                    "Top 25 Tense Errors SSC Exams",
                    "Bank PO English: Hard Tense Questions",
                    "Tense Error for CDS & NDA (Bilingual)",
                    "SSC Sentence Improvement Tense Practice",
                    "Common Tense Mistakes in Spoken English",
                    "Mega Revision Quiz: 50 Tense Questions",
                ],
            },
            {
                name: "Active-Passive & Direct-Indirect Speech",
                postRange: "Posts 186–200",
                topicCount: 15,
                topics: [
                    "Voice Change: All Tenses Active to Passive",
                    "Passive of Imperative (Let and Should rules)",
                    "Passive of Interrogative (Who becomes By Whom)",
                    "Verbs with two objects (Direct/Indirect rules)",
                    "Infinitive Passive (To be + V3) and Gerund Passive",
                    "Direct to Indirect: Pronoun Change (SON formula)",
                    "Tense Change when reporting verb is past",
                    "Exceptions: Universal Truths, Habitual Actions",
                    "Narration of Interrogative (If/Whether rules)",
                    "Narration of Imperative (Command/Request/Suggest)",
                    "Narration of Exclamatory & Optative",
                    "Top 25 Voice & Narration SSC PYQs",
                    "Sentence Improvement Voice/Narration",
                    "Voice/Narration Error NDA, CDS, State PCS",
                    "Mega Revision Quiz: 50 Voice/Narration Questions",
                ],
            },
        ],
    },
    {
        id: "cat-2",
        name: "Topic-wise Vocabulary (Micro-Niche)",
        nameHindi: "विषय-वार शब्दावली",
        slug: "topic-wise-vocabulary",
        icon: "🏷️",
        description:
            "Domain-specific vocabulary lists organized by real-world topics. Each post covers 30–50 English words with Hindi meanings, example sentences, and memory tricks for a specific topic.",
        totalPosts: 180,
        postRange: "Posts 411–590",
        subCategories: [
            {
                name: "Medical & Health",
                postRange: "Posts 411–425",
                topicCount: 15,
                topics: [
                    "Disease Names in English with Hindi Meaning",
                    "Human Body Parts in English (A to Z with Hindi)",
                    "Medicine & Pharmacy Vocabulary (English-Hindi)",
                    "Doctor Specializations in English (Cardiologist, etc.)",
                    "Fitness & Exercise Vocabulary with Hindi",
                    "Hospital Equipment Names in English-Hindi",
                    "Mental Health Vocabulary with Hindi Meanings",
                    "First Aid Vocabulary with Bengali/Hindi Translation",
                    "Symptoms & Illnesses: English to Hindi Guide",
                    "Dental Vocabulary: English-Hindi Terms",
                    "Eye Care Vocabulary with Hindi Meanings",
                    "Skin & Hair Care Vocabulary (Bilingual)",
                    "Yoga & Meditation English Words with Hindi",
                    "Pregnancy & Childbirth Vocabulary (Bilingual)",
                    "Ayurveda & Herbs Vocabulary with Hindi Names",
                ],
            },
            {
                name: "Business, Law & Corporate",
                postRange: "Posts 426–445",
                topicCount: 20,
                topics: [
                    "Court & Legal Terms in English-Hindi",
                    "Banking Vocabulary: English Terms with Hindi",
                    "Stock Market Terms in English (Hindi Explained)",
                    "Office Email Vocabulary with Hindi Meanings",
                    "Business Deal & Negotiation Terms (Bilingual)",
                    "Accounting Terms in English-Hindi",
                    "Insurance Vocabulary with Hindi Meanings",
                    "Tax & Finance Terms (Bilingual Guide)",
                    "Contract & Agreement Vocabulary in Hindi",
                    "Company & Management Terms (English-Hindi)",
                    "Real Estate Vocabulary with Hindi Translation",
                    "Marketing & Advertising Terms in Hindi",
                    "Human Resources Vocabulary (Bilingual)",
                    "Import-Export & Trade Terms with Hindi",
                    "Bankruptcy & Debt Vocabulary in Hindi",
                    "Corporate Law Terms: English to Hindi",
                    "Cyber Law & IT Act Vocabulary (Bilingual)",
                    "Intellectual Property Terms (Copyright, Patent)",
                    "Employment & Labor Law Vocabulary in Hindi",
                    "E-commerce Vocabulary with Hindi Meanings",
                ],
            },
            {
                name: "Human Emotions & Behavior",
                postRange: "Posts 446–475",
                topicCount: 30,
                topics: [
                    "Personality Traits in English (Positive) with Hindi",
                    "Personality Traits in English (Negative) with Hindi",
                    "Facial Expressions in English-Hindi",
                    "Anger & Frustration Vocabulary with Hindi",
                    "Happiness & Joy: English Words in Hindi",
                    "Sadness & Grief Vocabulary (Bilingual)",
                    "Fear & Anxiety Words in English-Hindi",
                    "Love & Affection Vocabulary with Hindi",
                    "Surprise & Shock: English Words in Hindi",
                    "Jealousy & Envy Vocabulary (Bilingual)",
                    "Confidence & Courage Words in Hindi",
                    "Confusion & Doubt Vocabulary (English-Hindi)",
                    "Emotional Intelligence Terms in Hindi",
                    "Body Language Vocabulary with Hindi Meanings",
                    "Tone & Voice Modifiers in English-Hindi",
                    "Mood & Temperament Words in Hindi",
                    "Stress & Burnout Vocabulary (Bilingual)",
                    "Patience & Tolerance Words in Hindi",
                    "Curiosity & Interest Vocabulary (English-Hindi)",
                    "Gratitude & Appreciation Words in Hindi",
                    "Forgiveness & Mercy Vocabulary (Bilingual)",
                    "Trust & Loyalty Words in English-Hindi",
                    "Ambition & Motivation Vocabulary in Hindi",
                    "Pride & Arrogance Words (Bilingual)",
                    "Shyness & Embarrassment Vocabulary",
                    "Boredom & Apathy Words in Hindi",
                    "Determination & Persistence in Hindi",
                    "Regret & Remorse Vocabulary (Bilingual)",
                    "Optimism & Pessimism Words in Hindi",
                    "Vocabulary for Describing People (Bilingual)",
                ],
            },
            {
                name: "Home & Household",
                postRange: "Posts 476–510",
                topicCount: 35,
                topics: [
                    "Kitchen Utensils Names in English-Hindi",
                    "Spices Names in English with Hindi Translation",
                    "Furniture Names in English-Hindi",
                    "Clothing & Fabric Names in Hindi",
                    "Electrical Appliances in English-Hindi",
                    "Cleaning Tools Vocabulary (Bilingual)",
                    "Bathroom Items in English-Hindi",
                    "Bedroom Vocabulary with Hindi Meanings",
                    "Living Room Items in English-Hindi",
                    "Gardening Tools & Plants Vocabulary",
                    "Home Repairs & Tools in Hindi",
                    "Plumbing Vocabulary: English-Hindi",
                    "Sewing & Tailoring Terms in Hindi",
                    "Party & Decoration Vocabulary (Bilingual)",
                    "Home Safety & Security Terms in Hindi",
                ],
            },
            {
                name: "Nature, Animals & Science",
                postRange: "Posts 511–540",
                topicCount: 30,
                topics: [
                    "Animals Names in English-Hindi (Mammals)",
                    "Birds Names in English-Hindi",
                    "Animal Sounds Vocabulary with Hindi",
                    "Baby Animals Names in English-Hindi",
                    "Sea Creatures Names in Hindi",
                    "Reptiles & Insects in English-Hindi",
                    "Trees & Plants Names in Hindi",
                    "Flowers Names in English-Hindi",
                    "Fruits Names in English-Hindi",
                    "Vegetables Names in English-Hindi",
                    "Weather & Natural Disasters Vocabulary",
                    "Space & Universe Terms in Hindi",
                    "Geography Terms in English-Hindi",
                    "Environmental Science Vocabulary (Bilingual)",
                    "Chemistry Lab Terms in English-Hindi",
                    "Physics Vocabulary with Hindi Meanings",
                    "Biology Terms in English-Hindi",
                    "Solar System Vocabulary in Hindi",
                    "Oceans & Rivers Vocabulary (Bilingual)",
                    "Mountain & Landscape Terms in Hindi",
                ],
            },
            {
                name: "Miscellaneous Nouns & Topics",
                postRange: "Posts 541–590",
                topicCount: 50,
                topics: [
                    "Grains & Cereals Names in English-Hindi",
                    "Pulses & Legumes Names in Hindi",
                    "Dry Fruits Names in English-Hindi",
                    "Metals & Minerals Names in Hindi",
                    "Sports Vocabulary in English-Hindi",
                    "Musical Instruments Names in Hindi",
                    "Vehicles Names in English-Hindi",
                    "Professions & Jobs in Hindi",
                    "School Subjects in English-Hindi",
                    "Colors & Shades Names in Hindi",
                    "Shapes & Geometry Terms in Hindi",
                    "Festivals Vocabulary in English-Hindi",
                    "Indian Culture & Tradition Terms",
                    "Technology & Computer Terms in Hindi",
                    "Social Media Vocabulary in Hindi",
                    "Cooking Methods Vocabulary (Bilingual)",
                    "Taste & Texture Words in English-Hindi",
                    "Building & Architecture Terms in Hindi",
                    "Road & Transport Vocabulary (Bilingual)",
                    "Phone & Communication Terms in Hindi",
                    "Time & Calendar Vocabulary in Hindi",
                    "Numbers & Counting in English-Hindi",
                    "Directions & Locations in Hindi",
                    "Countries & Nationalities in Hindi",
                    "Religious Vocabulary in English-Hindi",
                    "Wedding & Ceremony Terms in Hindi",
                    "Family Relations in English-Hindi",
                    "Body Movements & Actions in Hindi",
                    "Hand Gestures & Actions in Hindi",
                    "Sounds & Noises Vocabulary (Bilingual)",
                    "Measurement Units in English-Hindi",
                    "Shapes & Patterns in Hindi",
                    "Art & Craft Vocabulary (Bilingual)",
                    "Photography Terms in English-Hindi",
                    "Film & Cinema Vocabulary in Hindi",
                    "Music Genres & Terms in Hindi",
                    "Dance Forms Vocabulary (Bilingual)",
                    "Food Preparation Terms in Hindi",
                    "Beverages & Drinks in English-Hindi",
                    "Breakfast Items Vocabulary in Hindi",
                    "Dinner & Lunch Items in Hindi",
                    "Snacks & Street Food in Hindi",
                    "Dairy Products in English-Hindi",
                    "Meat & Seafood Vocabulary in Hindi",
                    "Indian Sweets Names in English-Hindi",
                    "Cooking Utensils Part 2 in Hindi",
                    "Tableware & Cutlery in Hindi",
                    "Stationery Items in English-Hindi",
                    "Toy Names in English-Hindi",
                    "Luggage & Travel Items in Hindi",
                ],
            },
        ],
    },
    {
        id: "cat-1",
        name: "A to Z Vocabulary Series",
        nameHindi: "वर्णमाला आधारित शब्दकोश",
        slug: "a-to-z-vocabulary",
        icon: "🔤",
        description:
            "Complete A to Z vocabulary reference: each letter has 2-part posts for Daily Use Words, Verbs (V1/V2/V3), Adjectives, Nouns & Adverbs, and Synonyms & Antonyms — plus special review posts. Covers 260 posts total.",
        totalPosts: 260,
        postRange: "Posts 591–850",
        subCategories: [
            {
                name: "Daily Use Words (A to Z)",
                postRange: "Posts 591–642",
                topicCount: 52,
                topics: [
                    "Letter A (Part 1 & 2)",
                    "Letter B (Part 1 & 2)",
                    "Letter C (Part 1 & 2)",
                    "Letter D (Part 1 & 2)",
                    "Letter E (Part 1 & 2)",
                    "Letter F (Part 1 & 2)",
                    "Letter G (Part 1 & 2)",
                    "Letter H (Part 1 & 2)",
                    "Letter I (Part 1 & 2)",
                    "Letter J & K (combined)",
                    "Letter L (Part 1 & 2)",
                    "Letter M (Part 1 & 2)",
                    "Letter N (Part 1 & 2)",
                    "Letter O (Part 1 & 2)",
                    "Letter P (Part 1 & 2)",
                    "Letter Q & R (combined)",
                    "Letter R (Part 1 & 2)",
                    "Letter S (Part 1 & 2)",
                    "Letter T (Part 1 & 2)",
                    "Letter U & V (combined)",
                    "Letter W (Part 1 & 2)",
                    "Letter X, Y & Z (combined)",
                    "Top 100 Most Important Daily Words (Review)",
                    "200 Basic English Words for Beginners",
                    "500 Daily Use Words PDF Download",
                    "Words Used in Daily Conversation at Home",
                    "Daily Use Vocabulary with Sentences",
                    "50 Words Hindi Speakers Mispronounce",
                    "Memory Tricks for Daily Use Words",
                    "Mega Practice Quiz: 100 Words (MCQ)",
                ],
            },
            {
                name: "Verbs (A to Z with V1/V2/V3)",
                postRange: "Posts 643–694",
                topicCount: 52,
                topics: [
                    "Letters A through Z: Each letter gets 2 posts (Part 1 & Part 2) covering verbs with three forms (V1, V2, V3) and Hindi meanings",
                    "100 Most Common Weak Verbs with Hindi Meanings",
                    "100 Most Common Strong (Irregular) Verbs",
                    "Confusing Irregular Verbs & Three Forms",
                    "Auxiliary & Modal Verbs Forms and Usage",
                    "Verbs that don't change (Cut, Put, Shut)",
                    "Double Past Forms (Hung vs Hanged, Lied vs Laid)",
                    "Verb Forms in SSC Sentence Improvement PYQs",
                    "30 Action Verbs for Spoken English",
                    "Root Verbs & Prefix-Suffix Formation",
                    "Verbs ending in ED/ING as Adjectives",
                    "How to Identify Verbs in Sentences",
                    "State Verbs vs Action Verbs (Continuous Rules)",
                    "Transitive vs Intransitive Verbs",
                    "Mega Quiz: Verb Forms (MCQ)",
                ],
            },
            {
                name: "Adjectives (A to Z)",
                postRange: "Posts 695–746",
                topicCount: 52,
                topics: [
                    "Letters A through Z: Each letter gets 2 posts covering adjectives with Hindi meanings and sentences",
                    "100 Positive Adjectives for Personality",
                    "100 Negative Adjectives with Hindi Meanings",
                    "Participle Adjectives (-ing and -ed rules)",
                    "Double Comparative/Superlative to Avoid",
                    "Compound Adjectives with Hindi Examples",
                    "Adjectives in SSC & Bank Cloze Tests",
                    "50 Advanced Adjectives for Essay Writing",
                    "Quantitative vs Qualitative Adjectives",
                    "Adjectives ending in ABLE and IBLE",
                    "Adjectives of Size, Shape, Age",
                    "Noun to Adjective Conversion (Suffix Rules)",
                    "Top Adjective Errors in NDA/CDS Papers",
                    "Sensible vs Sensitive (Common Confusions)",
                    "Mega Quiz: Adjectives (MCQ)",
                ],
            },
            {
                name: "Nouns & Adverbs (A to Z)",
                postRange: "Posts 747–798",
                topicCount: 52,
                topics: [
                    "Letters A through Z: Each letter gets 2 posts covering nouns and adverbs with Hindi meanings",
                    "Abstract Nouns with Hindi Meanings",
                    "Concrete vs Abstract Nouns (Hindi Examples)",
                    "Noun Suffixes: Verb/Adjective to Noun",
                    "100 Most Common Adverbs of Manner",
                    "Adverbs of Frequency with Sentences",
                    "Adjective vs Adverb ending in LY",
                    "Position of Adverbs (Rules & Exceptions)",
                    "Adverbs of Time and Place",
                    "Common Noun Mistakes Hindi-Medium Students",
                    "Relative Adverbs (When, Where, Why)",
                    "Abstract Nouns in Bank PO/Clerk Exams",
                    "Identify Adverbs in RC Passages",
                    "30 Adverbs for Spoken English",
                    "Mega Quiz: Nouns & Adverbs (MCQ)",
                ],
            },
            {
                name: "Synonyms & Antonyms (A to Z)",
                postRange: "Posts 799–850",
                topicCount: 52,
                topics: [
                    "Letters A through Z: Each letter gets 2 posts covering synonyms and antonyms with Hindi meanings",
                    "Top 100 Repeated Synonyms SSC CGL (2018-2026)",
                    "Top 100 Repeated Antonyms in SSC Exams",
                    "High-Level Synonyms for SBI PO & IBPS PO",
                    "High-Level Antonyms for Banking Mains",
                    "Synonyms & Antonyms in NDA & CDS PYQs",
                    "Prefix/Suffix Rules to find Antonyms",
                    "50 Confusing Words with Similar Synonyms",
                    "TCS Pattern Synonyms in SSC Selection Post",
                    "Synonyms/Antonyms in State PCS Exams",
                    "Synonyms/Antonyms in SSC MTS & CPO",
                    "How to Solve Synonym/Antonym Questions",
                    "100 Difficult Words from The Hindu",
                    "Daily Use Synonyms & Antonyms",
                    "Mega Quiz: 100 Synonyms & Antonyms (MCQ)",
                ],
            },
        ],
    },
    {
        id: "cat-5",
        name: "Daily Sentences & Spoken English",
        nameHindi: "दैनिक वाक्य और बोलचाल की अंग्रेज़ी",
        slug: "daily-sentences-spoken-english",
        icon: "💬",
        description:
            "Practical English for Hindi-medium speakers: situation-based conversations (bank, hospital, restaurant, interview), grammatical speaking structures, and emotion-based daily sentences.",
        totalPosts: 150,
        postRange: "Posts 851–1000",
        subCategories: [
            {
                name: "Situation-Based Conversations",
                postRange: "Posts 851–900",
                topicCount: 50,
                topics: [
                    "English Conversation at the Bank",
                    "English Conversation at the Hospital with Doctor",
                    "English at a Restaurant: Ordering Food",
                    "How to Introduce Yourself in a Job Interview",
                    "English at a Shopping Mall",
                    "Conversation with a Shopkeeper (Grocery)",
                    "Asking for and Giving Directions",
                    "English at the Railway Station",
                    "English at the Airport & Check-in",
                    "Booking a Cab or Taxi",
                    "Talking to a Landlord about Rent",
                    "Conversing with a New Neighbor",
                    "Calling Customer Care",
                    "Parent-Teacher Meeting English",
                    "Making a Complaint (Defective Product)",
                    "Small Talk with Office Colleagues",
                    "Introducing a Friend/Family Member",
                    "Talking about Hobbies and Interests",
                    "Ordering Products Online",
                    "Inviting Someone to a Party",
                    "Accepting/Declining Invitations Politely",
                    "Conversing with a Doctor about Symptoms",
                    "English at a Post Office",
                    "Talking to a Hairdresser/Barber",
                    "English at a Gym with Trainer",
                    "Talking about Daily Routine",
                    "Discussing Weekend Plans",
                    "Hotel Front Desk: Checking In",
                    "Checking Out of a Hotel",
                    "Asking for Help or Favors Politely",
                    "Congratulating Someone (Success/Wedding)",
                    "Expressing Sympathy & Condolences",
                    "Talking to a Pharmacist about Medicine",
                    "English at a Library",
                    "Discussing Weather and Seasons",
                    "Conversing with a Police Officer",
                    "Technical Support: Computer/Internet issues",
                    "Arguing and Resolving Conflicts Politely",
                    "Talking to Kids in English",
                    "Discussing Studies & Exam Prep with Classmates",
                    "English at a Movie Theater",
                    "Talking about Sports and Games",
                    "Conversing with a Travel Agent",
                    "Talking to a Tailor about Measurements",
                    "Asking for Time or Date Politely",
                    "Conversation about Healthy Habits",
                    "Discussing a Movie or Book",
                    "Talking to a Mechanic (Car/Bike Repair)",
                    "Dealing with Late Arrival: Apologizing",
                    "Practice Quiz: Situation-Based Conversations",
                ],
            },
            {
                name: "Grammatical Structures in Speaking",
                postRange: "Posts 901–950",
                topicCount: 50,
                topics: [
                    "USED TO in Sentences (Hindi Meanings)",
                    "HAD BETTER (Advice/Suggestion)",
                    "WOULD RATHER (Preference)",
                    "SHOULD HAVE / COULD HAVE / WOULD HAVE",
                    "IS/AM/ARE TO and WAS/WERE TO",
                    "HAS/HAVE TO and HAD TO (Necessity)",
                    "WILL HAVE TO (Future Necessity)",
                    "AS IF and AS THOUGH (Hypothetical)",
                    "NO MATTER WHAT (Regardless)",
                    "GOING TO (Gonna) and WANT TO (Wanna)",
                    "FEEL LIKE + V-ing (Mann kar raha hai)",
                    "IT'S TIME + V2 (Time to do something)",
                    "I WISH (Hypothetical/Kash aisa hota)",
                    "KEEP ON and GO ON (Karte rahna)",
                    "START and STOP with V-ing",
                    "INSTEAD OF and BESIDES",
                    "FOR THE SAKE OF and ON BEHALF OF",
                    "BY THE WAY and ANYWAY",
                    "IN ORDER TO and SO THAT",
                    "WHETHER...OR (Whether ye ho ya woh)",
                    "AS SOON AS and THE MOMENT",
                    "UNLESS and UNTIL (Jab tak ki)",
                    "THERE IS NO USE OF / NO POINT IN",
                    "SENSING/SEEING in Conversation",
                    "BY ALL MEANS and BY NO MEANS",
                    "MEANWHILE and IN THE MEANTIME",
                    "SO CALLED and SO TO SAY",
                    "AS FAR AS... IS CONCERNED",
                    "IN SPITE OF and DESPITE (Ke bawajood)",
                    "ACCORDING TO and IN MY OPINION",
                    "HAD IT NOT BEEN FOR (Advanced)",
                    "GET + Object + V3 (Causative Verbs)",
                    "MAKE + Person + V1 (Causative Verbs)",
                    "LET ALONE (To door ki baat hai)",
                    "HOW ABOUT + V-ing (Kaisa rahega)",
                    "WHAT IF (Kya hoga agar)",
                    "TO BE HONEST and FRANKLY SPEAKING",
                    "ALL OF A SUDDEN and SUDDENLY",
                    "MORE OFTEN THAN NOT (Aam taur par)",
                    "AT ANY COST / BY HOOK OR BY CROOK",
                    "SOONER OR LATER (Aaj nahi to kal)",
                    "FOR THE TIME BEING (Filhaal ke liye)",
                    "ONCE IN A WHILE and SELDOM (Kabhi kabhar)",
                    "IN THE LONG RUN (Lambe samay mein)",
                    "TO SOME EXTENT and PARTIALLY",
                    "FIRST OF ALL and LAST BUT NOT LEAST",
                    "WITHOUT FAIL (Bina chuke)",
                    "IN VAIN (Vyarth mein)",
                    "Willy-Nilly (Chahe-anchahe)",
                    "Practice Quiz: Grammatical Structures",
                ],
            },
            {
                name: "Daily Use Sentences by Emotions",
                postRange: "Posts 951–1000",
                topicCount: 50,
                topics: [
                    "Morning Routine Sentences",
                    "Night Routine & Sleeping Sentences",
                    "Express Anger and Frustration",
                    "Express Sadness and Sorrow",
                    "Express Happiness and Joy",
                    "Express Surprise and Shock",
                    "Apologize Politely",
                    "Say Thank You & Show Gratitude",
                    "Congratulate & Wish Luck",
                    "Encourage & Motivate Someone",
                    "Warn or Caution Someone",
                    "Give Advice and Suggestions",
                    "Make Requests Politely",
                    "Ask for Permission",
                    "Daily Sentences with Kids",
                    "School & Homework Sentences",
                    "Office & Meetings Sentences",
                    "Shopping & Bargaining Sentences",
                    "Travel & Journey Sentences",
                    "Food & Dining Sentences",
                    "Health & Sickness Sentences",
                    "Weather & Temperature Sentences",
                    "Telephone Etiquette in English",
                    "WhatsApp & Chatting Short Sentences",
                    "Romantic English Sentences with Hindi",
                    "Express Doubt and Confusion",
                    "Express Boredom and Tiredness",
                    "Praising & Complimenting Someone",
                    "Welcoming Guests at Home",
                    "Saying Goodbye and Farewell",
                    "Short Sentences (2-3 Words Only)",
                    "Exclamatory Sentences with Hindi",
                    "Modal Verbs: Can, Could, May in Speaking",
                    "Modal Verbs: Should, Must, Would",
                    "Express Urgency or Hurry",
                    "Complain about Neighbors or Noise",
                    "Festival & Birthday Wishes",
                    "Common English Proverbs (Hindi Equivalents)",
                    "Housework & Chores Sentences",
                    "Agreement and Disagreement Expressions",
                    "Interrupt Someone Politely",
                    "Describing a Past Event or Incident",
                    "Talking about Future Goals",
                    "Kitchen & Cooking Sentences",
                    "Hunger and Thirst Expressions",
                    "Asking about Someone's Health",
                    "Calm Someone Down",
                    "Verbs of Sensation: Taste, Smell, Look",
                    "100 Most Common Sentences PDF Download",
                    "Mega Practice Quiz: 100 Sentences (MCQ)",
                ],
            },
        ],
    },
];

export const roadmapFormulas: Formula[] = [
    {
        name: "PYQ Exam Specific Formula",
        description:
            "Top [10/20/50] [Idioms/Phrasal Verbs/Synonyms/Antonyms] for [SSC CGL / CHSL / MTS / CPO / IBPS PO / SBI PO / RBI Grade B / NDA / CDS] with Hindi Meaning.",
        example:
            "Top 20 Phrasal Verbs for SBI PO 2026 with Hindi Meanings & PYQs",
        estimatedTopics: 108,
    },
    {
        name: "Grammar Rule Formula",
        description:
            "[Noun/Pronoun/Adjective/Adverb/Preposition/Conjunction/Tenses/Voice/Narration] Error Detection Rules for [SSC CGL / Bank PO / NDA] (In Hindi).",
        example:
            "Noun Error Detection Rules for Bank PO with Hindi Translation",
        estimatedTopics: 27,
    },
    {
        name: "Daily News / The Hindu Formula",
        description:
            "The Hindu Editorial Vocabulary for [Date/Month/Topic] with Hindi Translation. Infinite topics from current affairs.",
        example:
            "The Hindu Editorial Vocabulary 15 June 2026 with Hindi Meanings",
        estimatedTopics: -1, // infinite
    },
    {
        name: "Micro-SEO 'Meaning in Hindi' Formula",
        description:
            "Pick ANY confusing word pair, phrasal verb, or idiom. '[Word/Idiom]' Meaning in Hindi (With SSC Previous Year Questions).",
        example:
            "'A blessing in disguise' Meaning in Hindi with SSC CGL PYQ Examples",
        estimatedTopics: -1, // thousands
    },
];
